### PR TITLE
Added SSH Keys talk and example ssh config file

### PR DESCRIPTION
**Pull request by abatten**
I added my SSH keys talk with some additional slides on what we talked about after we crated the keys.

There is also an example config file for some people to use if they change USERNAME

### CODE REVIEW

**Comment by abatten** [comment]
This is the resolution to #18

**Comment by abatten** [comment]
Just so we are prepared the slides are only 114KB. :P

**Comment by manodeep** [comment]
I removed the offending commit with the large pdf file but since your PR was based on that commit, accepting this PR will once again add the large mpi4py pdf into the master. Do you mind deleting this PR and creating a new one off the current master?

(I think a git pull should update your version to this one on github, but you might need a `-f` flag since the history was re-written)

**Comment by abatten** [comment]
Since I have a fork of the SwinCas directory and my fork has the large file how do I update mine? Would it be easier to just delete my fork and create a new one with my files?

**Comment by manodeep** [comment]
You can do the same process for removing the last commit. Jacob and I did the following two steps from [here](https://gist.github.com/gunjanpatel/18f9e4d1eb609597c50c2118e416e6a6)

```sh
git reset HEAD^ --hard
git push origin -f
```

Or delete the fork and start over, if you prefer. That should always work :)

**Pull request closed without merging**
