### PR TITLE
Added SSH key slides at the request of Jacob #18

### PR DESCRIPTION
**Pull request by abatten**
New Pull request for SSH keys slides at the request of #18.

### CODE REVIEW

**Comment by manodeep** [comment]
Will you please also add an entry to the `index.rst` file at the root of the repo?

**Comment by abatten** [comment]
Yep, `index.rst`is now updated.

**Comment by manodeep** [comment]
Sorry - one more thing. Will you please explain what the `PROXYCOMMAND` is doing in the `config`? The rest of the entries in the `config` file are reasonably obvious.

**Comment by manodeep** [comment]
Or is this a task better suited for @coljac ?

**Comment by coljac** [comment]
Looks good now!

**Pull request merged**
